config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :logins, only: [:new, :create, :destroy]
  get 'registrations/new'
  get 'registrations/destroy'
  get 'logins/new'
  get 'logins/destroy'
  post '/register' => 'registrations#create'
  post '/logins' => 'logins#create'
  get 'logout', to: 'logins#destroy', as: 'logout'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :name , presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    if session[:user_id]
        @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def new

  end

  def create

    user = User.find_by(email:login_params[:email])
    if user && user.authenticate(login_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      redirect_to logins_new_path, notice: "Invalid credentials"
    end

  end

  def destroy
   session[:user_id] = nil
   redirect_to root_url, notice: "Logged out!"
  end

  private 
    def login_params
      params.require(:log).permit(:email, :password)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  
  def new

  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id]=user.id
      redirect_to home_index_path, notice: "User Created"
    else 
      redirect_to home_index_path, notice: "Error Creating User"
    end
  end

  def destroy

  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :confirm_password)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/index.html.erb
<h1 align="center"><b>Welcome to the Portal</b></h1>
<hr width="150px" align="center"/>
<br />
<br />
<center>
<% if @current_user %>
 <h3>Hello <%= @current_user.name %>, Welcome to the site
 </h3>
  <br />
 <%= link_to 'Log Out', logout_path%>
<% else %>
<%= link_to 'Sign Up', registrations_new_path %> <t /> or 
 <%= link_to 'Log In', logins_new_path %>
<% end %>
<p id='notice'><%= notice %></p>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Regandlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/destroy.html.erb
<h1>Logins#destroy</h1>
<p>Find me in app/views/logins/destroy.html.erb</p>

app/views/logins/new.html.erb
<h1 align="center"><b>Login</b></h1>
<hr width="100px" align="center"/>
<br />
<center>
<form action="/logins" method="POST">
	<input type="hidden" name="authenticity_token" value="<%form_authenticity_token%>">
<label><b>Email :</b></label>
<input type="email" name="log[email]" placeholder="email" />
<br />
<br />
<label><b>Password :</b></label>
<input type="password" name="log[password]" placeholder="password"/>
<br />
<br />
<input type="submit" value="submit" class="submit"/><t />
<br />
</form>
<br />
	<%= link_to 'New User ? Register here', registrations_new_path %>
	<br />
<br />
	<%= link_to 'Back to home', home_index_path %>
<center><p id='notice'><%= notice %></p></center>